[server]
port = 8000
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor="#1A4CAE"
secondaryBackgroundColor="#F8F9FA"
textColor="#47515C"
